### PR TITLE
feat: implement markdown blog post functionality

### PR DESCRIPTION
**Pull request by braaar**
Still a work in progress, but the most important functionality is there.
- Blog post pages are generated from markdown files place in a specific folder
- Markdown frontmatter sets up things like cover image URL, date, etc.

### CODE REVIEW

**Comment by cobraz** [comment]
Seems like this doesn't work. Try the dev url: https://dev-bjerk-io--pr329-blog-d096g09n.web.app/

**Comment by braaar** [comment]
Pushed some changes now. Check `/blog` to see the behaviour of the new `ImageWrapper` component. I am struggling to make it so that it works for svg images and bitmaps

**Comment by braaar** [comment]
After a lot of funky business with Next Image we have now come full circle again. The build process is failing, because apparently there are images that don't have a loader set up for them?

**Review by cobraz — COMMENTED** [review]
Maybe we could remove the example blog articles and add actual articles from our old blog?

**Comment by cobraz** [comment]
Can we roll this out on `next`? I feel we should adjust this a little before landing.

**Pull request merged**
