### PR TITLE
feat: Mobile site view

### LINKED ISSUE #97: Mobile site view
Add mobile styling

### LINKED ISSUE #115: Text size and placement
As mentioned in PR #109 

> The text has the wrong size and weight – this is throughout the subpages.
> 
> This is how it looks now:
> image
> 
> And this is how it should look:
> image
> 
> Header is missing background on scroll.
> 
> Text underneath the pictures is also too small and squeezed:
> image

/cc: @AnneMatilde

### LINKED ISSUE #116: Font issue?
Skjermbilde 2021-03-25 kl  20 39 06

Fonts do not visibility look like TT Commons (Bjerk's font).
See the screenshot above (or video below). 

YouTube-video: https://youtu.be/x6xXY3G9D5U

### PR DESCRIPTION
**Pull request by dkostenko-bjerk**
Close #97 
Close #115 
Close #116

### CODE REVIEW

**Review by AnnaBjerk — CHANGES_REQUESTED** [review]
It doesn't look good on mobile. Not only text, but bug issues on the home screen and the design of X button + the navigation button is different from the original. I took some photos with my phone, will send those to you @dkostenko-bjerk

**Comment by dkostenko-bjerk** [comment]
The video in Safari/iOS does not work

**Comment by dkostenko-bjerk** [comment]
> "Safari hasn't fully implemented Webm support yet, so not much you can do until Apple adds that in place. ... Chrome and the other browsers on iOS still use the webview of Safari for rendering (Apple security rule)."

@cobraz should we use mp4 or choose depending on the browser/OS?

**Review by AnneMatilde — COMMENTED** [review]
This is looking great so far! I have a few comments.

Front page:
– Button on the top hero (front page) looks too small in height. Please check this.
– Can you make the images on the project tiles a bit taller (more square that rectangular)?

A few comments on the footer: 
- Less space between phone/email and address
- Hide the links in green for the moment ("Se ledige stillinger" and "Personvern")

Contact page:
- Fix line break in address

**Review by AnnaBjerk — CHANGES_REQUESTED** [review]
I agree when it comes to changes Anne Matilde has requested. Other than that, much better than yesterday! 😺 👍

**Review by AnnaBjerk — APPROVED** [review]

**Comment by dkostenko-bjerk** [comment]
> – Can you make the images on the project tiles a bit taller (more square that rectangular)?


@AnneMatilde I think I need cropped images for it

**Comment by AnnaBjerk** [comment]
> > – Can you make the images on the project tiles a bit taller (more square that rectangular)?
> 
> @AnneMatilde I think I need cropped images for it

Don't worry @AnneMatilde we figured it out now. The mobile view images are on slide 11 in your adobe design 👍

**Comment by AnneMatilde** [comment]
> > – Can you make the images on the project tiles a bit taller (more square that rectangular)?
> 
> @AnneMatilde I think I need cropped images for it

Ignore this, leave the images as they are 😊

**Review by AnneMatilde — COMMENTED** [review]
Looks a lot better! The contact form in the footer is too narrow now (doesn't follow container). And social icons in footer are not aligned. And I cant see a video in the front page hero? Otherwise it's good 😊

**Comment by AnnaBjerk** [comment]
> Looks a lot better! The contact form in the footer is too narrow now (doesn't follow container). And social icons in footer are not aligned. And I cant see a video in the front page hero? Otherwise it's good 😊

@AnneMatilde The video is a different issue. It doesn't show on iOS devices because of Safari's own issues. There is a new issue on this here #125

**Comment by AnnaBjerk** [comment]
@dkostenko-bjerk Please see Anne's comments on the design.

**Comment by dkostenko-bjerk** [comment]
@AnneMatilde it's done

**Comment by AnneMatilde** [comment]
The following are still issues:

- [ ] Width of contact form is not correct (not following container)
- [ ] Social icons alignment

_Tested on Chrome_

**Comment by dkostenko-bjerk** [comment]
@AnneMatilde Have you looked [here](https://deploy-preview-119--bjerk-website-dev.netlify.app/)? 
Containers widths fixed in #76

**Pull request closed without merging**
