### PR TITLE
fix: footers max-width

### LINKED ISSUE #63: Adjustment of the video on the homepage
The video has to be stretched out to fill out the screen. Right now it jumps to a small square halfway through. 
YouTube elements, such as title, photo of the owner of the video, share button and so on for example, have to be invisible.

### LINKED ISSUE #126: `max-width` on `<ContactFooter />` and `<Footer />`'s inner-container
image

The `<ContactFooter />` should scale to a maximum width (e.g. `1920px` like other elements). On the illustration/screenshot above, there are two a box (with red border). This box shows the container, of which you should find the title («Si hei») and other content. The background should be 100% of the window.

In other words:

https://github.com/bjerkio/website/blob/f8f1f25402d99c37ed96899f37a46d1529bd0b8d/web/src/components/layouts/components/contact-footer/contact-footer.tsx#L11-L15

Somewhere there 👆 it should be a `maxWidth: '100%'` (and probably some way to place it in center)

/cc @AnneMatilde @dkostenko-bjerk 

re #123

### PR DESCRIPTION
**Pull request by cobraz**
Alternative to #127

I've coordinated with @AnneMatilde, and done these extras:

- Removed video (replaced with solid gray color)
- Fixed inner-container on home page.

fixes #126
closes #127
closes #63

### CODE REVIEW

**Review by dkostenko-bjerk — COMMENTED** [review]
@cobraz Are we not going to add video to the home page (on 100vh)?

**Comment by cobraz** [comment]
The video we've added was temporary, and while lacking a new one @AnneMatilde choice to go with a gray background for now.

**Comment by AnneMatilde** [comment]
LGTM! But didn't we agree to have the contact form full width for now @cobraz?

**Review by AnneMatilde — COMMENTED** [review]
LGTM! But didn't we agree to have the contact form full width for now @cobraz?

**Comment by cobraz** [comment]
> @cobraz Are we not going to add video to the home page (on 100vh)?

@AnneMatilde said since it was grey to set it to 80vh.

**Comment by dkostenko-bjerk** [comment]
LTGM!

**Pull request merged**
