### PR TITLE
feat: Contact footer video

### LINKED ISSUE #82: Contact footer video
https://github.com/bjerkio/website/blob/ec5e112ff035ac8627e436010921e00318cf0e19/web/src/components/layouts/components/contact-footer/contact-footer.tsx#L60-L65

---

###### This issue was generated by [todo](https://todo.jasonet.co) based on a `TODO` comment in ec5e112ff035ac8627e436010921e00318cf0e19 when #78 was merged. cc @dkostenko-bjerk.

### PR DESCRIPTION
**Pull request by dkostenko-bjerk**
Close #82

### CODE REVIEW

**Review by cobraz — APPROVED** [review]
Lot of stuff happening, but I think I understood it all 🤞

LGTM!

**Review by AnneMatilde — COMMENTED** [review]
The image/video doesn't follow the right side margins. Also – we dont have a video ready for launch, so I say we just remove the video for now. What do you think @AnnaBjerk?

**Comment by cobraz** [comment]
> We dont have a video ready for launch, so I say we just remove the video for now. What do you think @AnnaBjerk?

Yes, we can just remove the play button for now.

**Comment by AnnaBjerk** [comment]
> > We dont have a video ready for launch, so I say we just remove the video for now. What do you think @AnnaBjerk?
> 
> Yes, we can just remove the play button for now.

@AnneMatilde I agree with @cobraz. Removing the play button seems like the best option for now.

**Comment by cobraz** [comment]
This has so much conflicting files, so I'm going to close this for now. From what I understand, the changes in this pull request aren't this huge. The git history is distorted AFAIK.


Closing, but please open a new :)

**Pull request closed without merging**
