### PR TITLE
feat: add intro cards to homepage

### PR DESCRIPTION
**Pull request by Xillians**

### CODE REVIEW

**Comment by FlemmingMP** [comment]
Looks great!

I'll look over it more in-depth, but if it seems ok code wise we can merge it into next and then debate design details.
To me the shadows feel like the wrong thing since we don't use anything like it anywhere on the website, but I can't think of something better either.

**Comment by Xillians** [comment]
image
the original idea was vaguely based on this. So what we can do is remove the shadow and instead implement one of the other themed colors we have for the background.

**Comment by FlemmingMP** [comment]
Nice! That looks pretty good.

**Comment by FlemmingMP** [comment]
Cards now extend to the "edges".

Screenshot 2024-08-08 at 15 36 56

**Review by FlemmingMP — APPROVED** [review]

**Pull request merged**
