### PR TITLE
Feat: The font size and placement

### LINKED ISSUE #67: The font size and placement
The font looks somewhat "squeezed".

This is what it looks like now: 

Screenshot 2021-03-17 15 53 09

And this is how the design looks like: 

Screenshot 2021-03-17 15 54 17

### PR DESCRIPTION
**Pull request by dkostenko-bjerk**
Close #67

### CODE REVIEW

**Review by cobraz — APPROVED** [review]

**Review by AnneMatilde — CHANGES_REQUESTED** [review]
Text looks a lot better! There are still some text that looks weird, please take a look at these:
image
image
image
image
Also, all body text on the sub pages.

**Comment by dkostenko-bjerk** [comment]
I think it would be more correct to fix this when all pages are merged

**Comment by AnneMatilde** [comment]
Yes, we can come back to this :-)

**Comment by cobraz** [comment]
> Yes, we can come back to this :-)

@dkostenko-bjerk which means this is ready to land 👍

**Pull request merged**
