### PR TITLE
feat: Localization

### LINKED ISSUE #23: Localization (i18n)
Nick and I have had a few talks about the fact that we would like to have an english-translation for the Bjerk site in a not so distant future. That fact would make adding some localization libraries make sense.

Considering we're using Gatsby, maybe we should consider adding the translations in build-time? Whats the standards for i18n for Gatsby users?

/cc @seacurrent @TanyaDolgopolova

### PR DESCRIPTION
**Pull request by dkostenko-bjerk**
Close #23

### CODE REVIEW

**Review by cobraz — COMMENTED** [review]
Wowza! That's a lot of files changed 👀

From what I understand, there are lots more than just i18n-related stuff here?

**Comment by AnnaBjerk** [comment]
@dkostenko-bjerk Please take a look at the comment above.

**Review by AnneMatilde — APPROVED** [review]
LGTM!

**Comment by dkostenko-bjerk** [comment]
@cobraz @AnnaBjerk Yes, there are a lot of commits because I needed to merge it with mobile-site-view branch, changes concerning this pr only in the last five commits

**Review by AnnaBjerk — APPROVED** [review]
In that case, let's go ahead with this

**Pull request closed without merging**
