### PR TITLE
refactor: Change architecture

### PR DESCRIPTION
**Pull request by cobraz**
👋 

Here comes yet another refactor. This one is huge, and to fully understand the number of improvements made you'll have to do a local checkout. The directory structure and all is IMHO much better like this.

- It's easier to understand how things work
- YAML is used for configured values
- MDX is used for content-first stuff (things we expect to change often: blogs, projects etc.)
- Most pages are converted to either `.tsx` or `.mdx`
- GraphQL Code Generator (aka generated types) for most GraphQL queries
- ☝ Used fragments
- Removed a bunch of unused components/code.

**Notice**: I've removed 7k and added 7k 🤷‍♂️ Hopefully at least 10-15% better!

### CODE REVIEW

**Review by AnneMatilde — APPROVED** [review]
LGTM!

**Comment by braaar** [comment]
I got this error the first time I ran `yarn dev` after installing. It disappeared in successive launches of the dev server, so no harm no foul, I guess?
```
Unexpected key "pageData" found in preloadedState argument passed to
createStore. Expected to find one of the known reducer keys instead: "nodes",
"logs", "pages", "redirects", "schema", "definitions", "staticQueryComponents",
"status", "webpack", "webpackCompilationHash", "config", "lastAction", "jobsV2",
 "pageDataStats", "components", "babelrc", "jobs", "nodesByType", "program",
"resolvedNodesCache", "nodesTouched", "flattenedPlugins",
"pendingPageDataWrites", "schemaCustomization", "inferenceMetadata",
"staticQueriesByTemplate", "queries", "visitedPages", "html". Unexpected keys
will be ignored.
```

Are we planning to localize the about page in English in a later PR?

**Comment by cobraz** [comment]
> I got this error the first time I ran `yarn dev` after installing. It disappeared in successive launches of the dev server, so no harm no foul, I guess?
> 
> ```
> Unexpected key "pageData" found in preloadedState argument passed to
> createStore. Expected to find one of the known reducer keys instead: "nodes",
> "logs", "pages", "redirects", "schema", "definitions", "staticQueryComponents",
> "status", "webpack", "webpackCompilationHash", "config", "lastAction", "jobsV2",
>  "pageDataStats", "components", "babelrc", "jobs", "nodesByType", "program",
> "resolvedNodesCache", "nodesTouched", "flattenedPlugins",
> "pendingPageDataWrites", "schemaCustomization", "inferenceMetadata",
> "staticQueriesByTemplate", "queries", "visitedPages", "html". Unexpected keys
> will be ignored.
> ```

Probably some `.cache` files?

> Are we planning to localize the about page in English in a later PR?

Yes :) I'm also planning to do an overhaul over all the English strings 👍

**Comment by braaar** [comment]
A couple of points:
- I see you have gone through the static assets and delected unused ones. is `simen-niklas.png` being used anywhere? It seems to be a low res composition of two photos that are found elsewhere in the site. 
- What is the intended distinction behind the `src/assets` vs. the `static` folder? I see `services-split.png` in one of them and `about-split.png`  in the other, two images that are to be used in the same way, no? I do like having employee photos in the same folder as the content files for projects and employees, though.

**Comment by braaar** [comment]
Otherwose, LGTM, as far as I can see from a cursory glance. I'm sure we'll find some issues to resolve down the road :wink:

**Comment by cobraz** [comment]
> A couple of points:
> 
> * I see you have gone through the static assets and delected unused ones. is `simen-niklas.png` being used anywhere? It seems to be a low res composition of two photos that are found elsewhere in the site.

No, that should probably be removed as well. If we're adding it back in, we could upload a new image with better resolution.

> * What is the intended distinction behind the `src/assets` vs. the `static` folder? I see `services-split.png` in one of them and `about-split.png`  in the other, two images that are to be used in the same way, no? I do like having employee photos in the same folder as the content files for projects and employees, though.

`static` is the folder we don't want to use. Files in `static` are uploaded without any optimalization or otherwise, which is bad. We probably want to refactor more in that regard 👍 

> Otherwise, LGTM, as far as I can see from a cursory glance. I'm sure we'll find some issues to resolve down the road 😉

There sure is! I know about at least a few 👍

**Comment by cobraz** [comment]
Okey, thanks for feedback! I'm merging this now 🎉

**Pull request merged**
